Repository Kibibit/tdd1t, pull requests merged in 2019-01, with the labels that each got.

#24 feat(tests-from-pull-requests): should return array of test names
  lib/tests-from-pull-request.js
Labels: PR: reviewed-approved

#31 feat(events): listen to the events related to tdd1t actions
  index.js
Labels: PR: unreviewed

#33 docs(homepage): show different subtitle on first install
  docs/index.html
  docs/js/index.js
Labels: PR: unreviewed

#39 ci(deploy): add now integration to deploy automatically
  now.json
Labels: PR: unreviewed

#40 docs(index.js): move probot comment outside of scope
  index.js
Labels: PR: unreviewed

#42 docs(homepage): fix homepage to point to the app and mention probot
  .vscode/settings.json
  docs/connect.png
  docs/css/style.css
  docs/index.html
  docs/issue.png
  docs/status-failed.png
  docs/status-passed.png
Labels: PR: unreviewed

#44 docs(homepage): fix image paths
  docs/index.html
Labels: PR: unreviewed

#45 ci(deployment): fix problem with zeit's now deployment on PRs
  now.json
Labels: PR: unreviewed

#46 docs(homepage): little nits + hide integration button after install
  docs/css/style.css
  docs/index.html
  docs/js/index.js
Labels: PR: unreviewed

#48 ci(demo-deployments): deploy without an app id for PR deployments
  deploy-pre-script.sh
  package.json
Labels: PR: unreviewed

#49 docs(homepage): text fix + docs link
  docs/css/style.css
  docs/github.svg
  docs/index.html
Labels: PR: reviewed-changes-requested
